
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:71 (enable_language)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.18.9-200.fc43.x86_64 - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "feature.cmake:65 (try_compile)"
      - "CMakeLists.txt:303 (FEATURE_CHECK_ASAN)"
    directories:
      source: "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp"
      binary: "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/home/kbtch_/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_C_FLAGS: " -O2 -Wall -pedantic -pipe -std=c99 -fPIC"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules;/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules;/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules;/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "LEXBOR_HAVE_ASAN"
      cached: true
      stdout: |
        Change Dir: '/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_f480f/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_f480f.dir/build.make CMakeFiles/cmTC_f480f.dir/build
        gmake[1] : on entre dans le répertoire « /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp »
        Building C object CMakeFiles/cmTC_f480f.dir/feature_check.c.o
        /home/kbtch_/emsdk/upstream/emscripten/emcc   -O2 -Wall -pedantic -pipe -std=c99 -fPIC  -MD -MT CMakeFiles/cmTC_f480f.dir/feature_check.c.o -MF CMakeFiles/cmTC_f480f.dir/feature_check.c.o.d -o CMakeFiles/cmTC_f480f.dir/feature_check.c.o -c /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/feature_check.c
        /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/feature_check.c:19:1: error: expected expression
           19 | }
              | ^
        1 error generated.
        gmake[1]: *** [CMakeFiles/cmTC_f480f.dir/build.make:82: CMakeFiles/cmTC_f480f.dir/feature_check.c.o] Error 1
        gmake[1] : on quitte le répertoire « /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp »
        gmake: *** [Makefile:134: cmTC_f480f/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "feature.cmake:120 (try_compile)"
      - "CMakeLists.txt:308 (FEATURE_CHECK_MSAN)"
    directories:
      source: "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp"
      binary: "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/home/kbtch_/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_C_FLAGS: " -O2 -Wall -pedantic -pipe -std=c99 -fPIC"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules;/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules;/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules;/home/kbtch_/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "LEXBOR_HAVE_MSAN"
      cached: true
      stdout: |
        Change Dir: '/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_eba19/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_eba19.dir/build.make CMakeFiles/cmTC_eba19.dir/build
        gmake[1] : on entre dans le répertoire « /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp »
        Building C object CMakeFiles/cmTC_eba19.dir/feature_check.c.o
        /home/kbtch_/emsdk/upstream/emscripten/emcc   -O2 -Wall -pedantic -pipe -std=c99 -fPIC  -MD -MT CMakeFiles/cmTC_eba19.dir/feature_check.c.o -MF CMakeFiles/cmTC_eba19.dir/feature_check.c.o.d -o CMakeFiles/cmTC_eba19.dir/feature_check.c.o -c /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/feature_check.c
        /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/feature_check.c:11:1: error: expected expression
           11 | }
              | ^
        1 error generated.
        gmake[1]: *** [CMakeFiles/cmTC_eba19.dir/build.make:82: CMakeFiles/cmTC_eba19.dir/feature_check.c.o] Error 1
        gmake[1] : on quitte le répertoire « /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/build_wasm/CMakeFiles/CMakeTmp »
        gmake: *** [Makefile:134: cmTC_eba19/fast] Error 2
        
      exitCode: 2
...
