<?php

/**
 * @author kbtch_
 * 
 * These classes are needed because Dom Object from php cannot be serialized.
 * They are just "mocked" values from C code, not real php object.
 * 
 * Comments (mostly) generated by claude with PAI (not by the author).
 * 
 * Mirror of the DOM spec nodeType constants (https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType).
 * PHP ext-dom assigns nodeType=13 to Dom\HTMLDocument instead of the spec value 9 (DOCUMENT_NODE).
 * PHP_HTML_DOCUMENT captures that deviation so it can be normalized at serialization time.
 */

interface NodeType {
    const ELEMENT_NODE = 1;
    const ATTRIBUTE_NODE = 2;
    const TEXT_NODE = 3;
    const CDATA_SECTION_NODE = 4;
    const ENTITY_REFERENCE_NODE = 5;
 	const ENTITY_NODE = 6;
    const PROCESSING_INSTRUCTION_NODE = 7;
    const COMMENT_NODE = 8;
    const DOCUMENT_NODE = 9;
    const DOCUMENT_TYPE_NODE = 10;
    const DOCUMENT_FRAGMENT_NODE = 11;
    const NOTATION_NODE = 12;
    const PHP_HTML_DOCUMENT = 13; // PHP-specific deviation from the DOM spec — not a standard nodeType
}

// Base serializable wrapper for any DOM node.
// Mirrors the Node interface from the DOM spec.
// Recursively serializes childNodes, dispatching each child to the appropriate subclass
// based on its nodeType. The PHP_HTML_DOCUMENT deviation (13) is normalized to DOCUMENT_NODE (9)
// here so all consumers (including the Vue reconstruction) see the spec-compliant value.
class LexborNode implements JsonSerializable {

    public int $nodeType = 0;
    public string $nodeName = '';
    public ?string $textContent = '';
    public ?array $childNodes = [];

    function __construct($node) {
        // node
        $this->nodeType = $node->nodeType ?? -1;
        if ($this->nodeType == NodeType::PHP_HTML_DOCUMENT)
        {
            // Normalize PHP's non-standard nodeType 13 to the spec-compliant DOCUMENT_NODE (9)
            // so that the Vue side can use Node.DOCUMENT_NODE without special-casing.
            $this->nodeType = NodeType::DOCUMENT_NODE;
        }
        $this->nodeName = $node->nodeName ?? '';
        $this->textContent = $node->textContent ?? '';
        
        // Recurse into children, dispatching each to its typed subclass.
        // Switching on the CHILD's nodeType (not the parent's) is intentional.
        foreach ($node->childNodes as $childNode)
        {
            switch ($childNode->nodeType)
            {
                case NodeType::ELEMENT_NODE:
                    array_push($this->childNodes, new LexborElement($childNode));
                    break;
                case NodeType::TEXT_NODE:
                    array_push($this->childNodes, new LexborText($childNode));
                    break;
                case NodeType::CDATA_SECTION_NODE:
                    array_push($this->childNodes, new LexborCDATASection($childNode));
                    break;
                case NodeType::COMMENT_NODE:
                    array_push($this->childNodes, new LexborComment($childNode));
                    break;
                case NodeType::DOCUMENT_NODE:
                    array_push($this->childNodes, new LexborHtmlDocument($childNode));
                    break;
                case NodeType::DOCUMENT_TYPE_NODE:
                    array_push($this->childNodes, new LexborDocumentType($childNode));
                    break;
                default:
                    array_push($this->childNodes, new LexborNode($childNode));
                    break;
            }
        }
    }

    function jsonSerialize(): mixed
    {
        return [
            // Node
            'nodeType' => $this->nodeType,
            'nodeName' => $this->nodeName,
            'childNodes' => array_values($this->childNodes),
            'textContent' => $this->textContent,
        ];
    }
}

// Mirrors the Text interface (extends CharacterData → Node).
// Adds wholeText, data and length — the fields specific to text nodes.
// CDATA sections share the same structure (see LexborCDATASection below).
class LexborText extends LexborNode {
    public string $wholeText = '';
    public string $data = '';
    public int $length = 0;

    function __construct($node) {
        // node
        parent::__construct($node);

        //Text
        $this->wholeText = $node->wholeText;
        $this->data = $node->data;
        $this->length = $node->length;
    }

    function jsonSerialize(): mixed
    {
        return parent::jsonSerialize() + [
            // Text
            'wholeText' => $this->wholeText,
            'data' => $this->data,
            'length' => $this->length,
        ];
    }
}

// CDATA sections are a subtype of Text in the DOM spec — same fields, different nodeType (4).
class LexborCDATASection extends LexborText {}

// Comment nodes only need the base Node fields (textContent holds the comment text).
// No additional properties required.
class LexborComment extends LexborNode {}

// Mirrors the Element interface (extends Node).
// Handles all element types: HTML, SVG, MathML.
// getAttributeNames() + getAttribute() works on Dom\Element (not just Dom\HTMLElement),
// so SVG/MathML attributes are correctly captured regardless of namespace.
// attributes are serialized as [{name, value}] to match what RenderElement expects in Vue.
// innerHTML is included for use as the string output in the pipe chain (result),
// not for the DOM reconstruction (which uses childNodes instead).
class LexborElement extends LexborNode {
    public ?string $namespaceURI = '';
    public string $localName;
    public string $tagName;
    public ?array $attributes = [];
    public string $innerHTML;
    public bool $isTemplate = false;

    function __construct($node) {
        //Node
        parent::__construct($node);

        // HtmlElement
        $this->namespaceURI = $node->namespaceURI ?? '';
        $this->localName = $node->localName ?? '';
        $this->tagName = $node->tagName ?? '';
        if (strtolower($this->tagName) === "template" && $this->namespaceURI === "http://www.w3.org/1999/xhtml")
            $this->isTemplate = true;
        foreach ($node->getAttributeNames() as $attributeKey)
        {
            array_push($this->attributes, array('name' => $attributeKey, 'value' => $node->getAttribute($attributeKey)));
        }
        $this->innerHTML = $node->innerHTML ?? '';
    }

    function jsonSerialize(): mixed
    {
        return parent::jsonSerialize() + [
            // Element / HtmlElement
            'namespaceURI' => $this->namespaceURI,
            'localName' => $this->localName,
            'tagName' => $this->tagName,
            'attributes' => array_values($this->attributes),
            'innerHTML' => $this->innerHTML,
            'isTemplate' => $this->isTemplate,
        ];
    }
}

// Mirrors the DocumentType interface (the <!DOCTYPE> node).
// In HTML5 documents, publicId and systemId are always empty strings,
// and internalSubset is null — only name ("html") carries meaningful information.
class LexborDocumentType extends LexborNode {
    public string $name = '';
    public string $publicId = '';
    public string $systemId = '';

    public function __construct($node)
    {
        parent::__construct($node);
        $this->name = $node->name;
        $this->publicId = $node->publicId;
        $this->systemId = $node->systemId;
    }

    public function jsonSerialize(): mixed
    {
        return parent::jsonSerialize() + [
            'name' => $this->name,
            'publicId' => $this->publicId,
            'systemId' => $this->systemId,
        ];
    }
}

// Mirrors the HTMLDocument interface (the root of the lexbor-parsed DOM tree).
// Dom\HTMLDocument has nodeType=13 in PHP — normalized to 9 (DOCUMENT_NODE) by LexborNode.
// childNodes contains [DocumentType, <html>] — the full tree is accessible through them.
// The document-level metadata (URL, charset, etc.) is included for completeness
// but is not consumed by the Vue reconstruction logic.
class LexborHtmlDocument extends LexborNode {
    public string $title;
    public string $URL;
    public string $documentURI;
    public string $characterSet;
    public string $charset;
    public string $inputEncoding;

    function __construct($node) {
        //Node
        parent::__construct($node);

        //Document
        $this->title = $node->title;
        $this->URL = $node->URL;
        $this->documentURI = $node->documentURI;
        $this->characterSet = $node->characterSet;
        $this->charset = $node->charset;
        $this->inputEncoding = $node->inputEncoding;
    }

    function jsonSerialize(): mixed
    {
        return parent::jsonSerialize() + [
            'title' => $this->title,
            'URL' => $this->URL,
            'documentURI' => $this->documentURI,
            'characterSet' => $this->characterSet,
            'charset' => $this->charset,
            'inputEncoding' => $this->inputEncoding,
        ];
    }
}
