TARGET = {0x3C: '<', 0x3E: '>', 0x22: '"', 0x27: "'", 0x3D: '=', 0x5C: '\\'}                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                            
results = []                                                                                                                   
                                                                                                                                                                                                                                                                                                                            
# Two-byte: lead 0x81-0xFE, trail 0x40-0xFE (excl 0x7F)                                                                                                                                                                                                                                                                      
for lead in range(0x81, 0xFF):                                                                                                                                                                                                                                                                                               
    for trail in range(0x40, 0xFF):                                                                                            
        if trail == 0x7F:                                                                                                                                                                                                                                                                                                    
            continue                                                                                                                                                                                                                                                                                                         
        seq = bytes([lead, trail])                                                                                                                                                                                                                                                                                           
        try:                                                                                                                                                                                                                                                                                                                 
            char = seq.decode('gb18030')                                                                                                                                                                                                                                                                                     
            utf8 = char.encode('utf-8')                                                                                                                                                                                                                                                                                      
            hits = [f"0x{b:02X}({TARGET[b]})" for b in utf8 if b in TARGET]                                                                                                                                                                                                                                                  
            if hits:                                                                                                                                                                                                                                                                                                         
                results.append((seq.hex().upper(), f"U+{ord(char):04X}", char, utf8.hex().upper(), hits))                                                                                                                                                                                                                    
        except Exception:                                                                                                                                                                                                                                                                                                    
            pass                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                            
for gb, cp, char, utf8, hits in results:                                                                                       
    print(f"GB:{gb} → {cp} ({char}) UTF-8:{utf8} — contient {', '.join(hits)}")