# CMake generated Testfile for 
# Source directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode
# Build directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[lexbor_unicode_composition_test]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/composition_test")
set_tests_properties([=[lexbor_unicode_composition_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;0;")
add_test([=[lexbor_unicode_edges_normalization_forms]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/edges_normalization_forms")
set_tests_properties([=[lexbor_unicode_edges_normalization_forms]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;0;")
add_test([=[lexbor_unicode_idna]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/idna")
set_tests_properties([=[lexbor_unicode_idna]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;0;")
add_test([=[lexbor_unicode_idna_codepoints]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/idna_codepoints")
set_tests_properties([=[lexbor_unicode_idna_codepoints]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;0;")
add_test([=[lexbor_unicode_idna_type]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/idna_type")
set_tests_properties([=[lexbor_unicode_idna_type]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;0;")
add_test([=[lexbor_unicode_normalization_forms]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/normalization_forms")
set_tests_properties([=[lexbor_unicode_normalization_forms]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;0;")
add_test([=[lexbor_unicode_normalization_forms_code_points]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/normalization_forms_code_points")
set_tests_properties([=[lexbor_unicode_normalization_forms_code_points]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/unicode/CMakeLists.txt;0;")
