# CMake generated Testfile for 
# Source directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css
# Build directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[examples_lexbor_css_StyleSheet]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/StyleSheet" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css/lexbor.css")
set_tests_properties([=[examples_lexbor_css_StyleSheet]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;24;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;0;")
add_test([=[examples_lexbor_css_selectors_list_easy_way]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/selectors/list_easy_way")
set_tests_properties([=[examples_lexbor_css_selectors_list_easy_way]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;24;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;0;")
add_test([=[examples_lexbor_css_selectors_list_fast_way]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/selectors/list_fast_way")
set_tests_properties([=[examples_lexbor_css_selectors_list_fast_way]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;24;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;0;")
add_test([=[examples_lexbor_css_syntax_structure_parse_file]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/syntax/structure_parse_file" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css/lexbor.css")
set_tests_properties([=[examples_lexbor_css_syntax_structure_parse_file]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;24;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;0;")
add_test([=[examples_lexbor_css_syntax_tokenizer_from_file]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/syntax/tokenizer/from_file" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css/lexbor.css")
set_tests_properties([=[examples_lexbor_css_syntax_tokenizer_from_file]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;24;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;0;")
add_test([=[examples_lexbor_css_syntax_tokenizer_print_raw]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/syntax/tokenizer/print_raw" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css/lexbor.css")
set_tests_properties([=[examples_lexbor_css_syntax_tokenizer_print_raw]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;24;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/examples/lexbor/css/CMakeLists.txt;0;")
