# CMake generated Testfile for 
# Source directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css
# Build directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[lexbor_css_declarations]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/declarations" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css/declarations")
set_tests_properties([=[lexbor_css_declarations]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_selectors_selectors]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/selectors/selectors")
set_tests_properties([=[lexbor_css_selectors_selectors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_selectors_specificity]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/selectors/specificity")
set_tests_properties([=[lexbor_css_selectors_specificity]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_stylesheet]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/stylesheet")
set_tests_properties([=[lexbor_css_stylesheet]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_syntax_an_plus_b]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/syntax/an_plus_b")
set_tests_properties([=[lexbor_css_syntax_an_plus_b]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_syntax_parser]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/syntax/parser" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css//syntax/parser")
set_tests_properties([=[lexbor_css_syntax_parser]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_syntax_style]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/syntax/style" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css/lexbor.css")
set_tests_properties([=[lexbor_css_syntax_style]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_syntax_tokenizer]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/syntax/tokenizer" "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/files/lexbor/css/syntax/tokenizer")
set_tests_properties([=[lexbor_css_syntax_tokenizer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;441;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
add_test([=[lexbor_css_syntax_tokenizer_queue]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/syntax/tokenizer_queue")
set_tests_properties([=[lexbor_css_syntax_tokenizer_queue]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;25;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/css/CMakeLists.txt;0;")
