# CMake generated Testfile for 
# Source directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core
# Build directory: /home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[lexbor_core_array]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/array")
set_tests_properties([=[lexbor_core_array]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_array_obj]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/array_obj")
set_tests_properties([=[lexbor_core_array_obj]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_avl]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/avl")
set_tests_properties([=[lexbor_core_avl]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_bst]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/bst")
set_tests_properties([=[lexbor_core_bst]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_bst_map]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/bst_map")
set_tests_properties([=[lexbor_core_bst_map]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_dobject]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/dobject")
set_tests_properties([=[lexbor_core_dobject]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_hash]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/hash")
set_tests_properties([=[lexbor_core_hash]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_in]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/in")
set_tests_properties([=[lexbor_core_in]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_mem]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/mem")
set_tests_properties([=[lexbor_core_mem]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_mraw]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/mraw")
set_tests_properties([=[lexbor_core_mraw]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
add_test([=[lexbor_core_str]=] "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/str")
set_tests_properties([=[lexbor_core_str]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/config.cmake;444;add_test;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;17;APPEND_TESTS;/home/kbtch_/Documents/MXSS_HtmlSanitizer_Symphony/lexbor-2.7.0/test/lexbor/core/CMakeLists.txt;0;")
